name: Publish
on:
  push:
    tags:
      - "v0.*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up OpenJDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: "temurin"
    - name: Publish
      run: |
        mkdir -p ~/.gem
        echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" > ~/.gem/credentials
        chmod 600 ~/.gem/credentials
        ./gradlew gem
        find ./build/gems -name 'embulk-filter-expand_json-*.gem' -maxdepth 1 -print0 | xargs -0 gem push --key github --host 'https://rubygems.pkg.github.com/st-tech'
